### ISSUE TITLE
API is not working

### ISSUE THREAD

**Issue by dasuarez** [meruff/go-trailhead-leaderboard-api#4]
<img width="1276" alt="Screen Shot 2020-06-10 at 4 47 42 PM" src="https://user-images.githubusercontent.com/13557656/84314598-b28b0a00-ab3e-11ea-84b5-0705a02d5111.png">

**Comment by meruff** [comment]
@dasuarez, as described in my recent commit 6ade6bf80848e7018c22f44ae5d9048aa43ac944, this is an issue with the `fwuid` becoming stale. I don't have a permanent fix for it other than updating the value manually. I can only get it from Trailhead by viewing the network tab in browser dev tools. I will need to find a way to solve this, but not sure when I will have time, or if a solution will be avilable. I suggest forking this repo and spinning up your own Heroku server to maintain that `fwuid` value yourself rather than relying on my hobbyist Heroku server that I use for my own needs.

I've just pushed another update to to the `fwuid` to this repo and my Heroku server that fixes it for now, but it will break again in the future. This is the second time it's become stale and has broke.
