### ISSUE TITLE
Points/Badges/Certification API's not working :(

### ISSUE THREAD

**Issue by jacobartz1223-git** [meruff/go-trailhead-leaderboard-api#7]
The Leader board solution was working really well 2 days ago and then it stopped pulling badges and certs etc.  

This endpoint gets an application error.  

https://go-trailhead-leaderboard-api.herokuapp.com/trailblazer/jartz1/certifications

but this endpoint seems to workj ust fine:

https://go-trailhead-leaderboard-api.herokuapp.com/trailblazer/jartz1/profile

**Comment by meruff** [comment]
Hi @jacobartz1223-git, as mentioned in issue #4, the `fwuid` parameter has become stale. If you look at my commit history [here](bdbdc010eab8d68bc15c036f8e0ad7c00c4e0281), [here](8fc2d1b8c289c95054c7fb5287483fd8f4587b5e), and [here](8fc2d1b8c289c95054c7fb5287483fd8f4587b5e), I've updated it several times recently, but it's always changing and I'll need to do it again in order for the callouts to the Trailhead Apex services to work. The current process is navigating to a Trailhead profile and inspecting the Network tab in the browser to see what request parameters are being sent. I'm currently seeking a fix for this so the API can either automatically grab it, or not require it (if you have any ideas please feel free to contribute). I'm just not sure what Trailhead expects if you don't send a `fwuid` parameter, cause it errors if a valid one isn't present. 

I'm also working on some error handling to display HTTP errors in PR #6 which should help prevent some of those Heroku application errors. But it still won't fix the `fwuid` parameter becoming stale whenever Trailhead values change.

You could also fork this repo and spin up your own Heroku site and deploy it if you need immediate access to the API at all times and update the `fwuid` when it goes down yourself.

**Comment by jacobartz1223-git** [comment]
@meruff   Well that is very frustrating.    The tool you built is really fantastic too bad the folks at TH keep "moving to goal posts".  I will talk to our engineering team and see if they have any ideas.

**Comment by meruff** [comment]
Yea I wouldn't say they're necessarily moving the goal post on me. It's working the way they intend it to. I'm just sorta piggy backing on their API, which isn't really public. This solution works for now. They could at any time decide to lock it down more and prevent me or others from accessing the data like this. They've done it in the past when they moved to Lightning Components on Trailhead. I built this API after they switched as it broke how my [Trailhead Leaderboard](https://github.com/meruff/trailhead-leaderboard) was scraping data on the old site. We'll see how it goes, maybe I can find a fix for the `fwuid` thing.

**Comment by PaulWeakley** [comment]
Good morning @meruff  Did some digging this morning and found that the fwuid is the same ID as the delegate version which can be found from a different API call.

https://trailblazer.me/c/ProfileApp.app?aura.format=JSON&aura.formatAdapter=LIGHTNING_OUT

returns JSON with a property of “delegateVersion” which matches a url encoded script address below which is why I think the delegate version is the same as the fwuid. Sample JSON and reference below. Should be able to make an initial request to the above link. Get the fwuid, and then proceed. I'd fork and make a PR but I'm not that familiar with Go so I wanted you to know first.

{
    "clientLibraries": [
        "https://trailblazer.me/jslibrary/1597351348000/ui-analytics-reporting/EclairNG.js"
    ],
    "delegateVersion": "axnV2upVY_ZFzdo18txAEw",
    "auraConfig": {
        "cssVariables": {

https://trailblazer.me/l/{"mode":"PROD","app":"c:ProfileApp","fwuid":"axnV2upVY_ZFzdo18txAEw","loaded":{"APPLICATION@markup://c:ProfileApp":"hrUxs-JL6LT7xe5JuRx5IQ"},"apce":1,"apck":"WOXBUDrPIPM_4An7aMMExw","mlr":1,"pathPrefix":"","dns":"c","ls":1,"ct":1}/bootstrap.js?ltngOut=true

**Comment by meruff** [comment]
@PaulWeakley this looks very promising! Let me play around with this and see what I find. Looks like from your description this could be just what we need.
